coverage:
  status:
    project:
      default:
        # basic
        target: 0
        threshold: 100%
        base: auto
        flags:
          - unit
        paths:
          - "src"
       # advanced
        branches:
          - master
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
